#!/usr/bin/env python3
"""Generate `docs/TOOLS.md` — the exhaustive capability catalog — from the live FastMCP server.

Introspects every registered tool (with its full input parameters), resource,
resource template, and prompt, then renders a Markdown catalog. This is the
single source of truth for "what can this server do, and with what arguments".

Run after adding/changing any tool/resource/prompt:

    make gen-tools-doc        # or: ./venv/bin/python scripts/gen_tools_doc.py

No EventKit permission is required — registration happens at import time via the
`@mcp.tool` / `@mcp.resource` / `@mcp.prompt` decorators; the EventKit store is
only opened later, inside the lifespan.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

# Importing the feature packages runs the decorators that register everything
# against the shared FastMCP instance in `server`.
from mcp_apple_reminders import prompts as _prompts  # noqa: F401
from mcp_apple_reminders import resources as _resources  # noqa: F401
from mcp_apple_reminders import tools as _tools  # noqa: F401
from mcp_apple_reminders.server import mcp

_OUT = Path(__file__).resolve().parent.parent / "docs" / "TOOLS.md"


def _param_type(spec: dict) -> str:
    """Render a JSON-schema property's type compactly (handles Optional/arrays)."""
    if "type" in spec:
        t = spec["type"]
        if t == "array":
            item_t = (spec.get("items") or {}).get("type")
            return f"array[{item_t}]" if item_t else "array"
        return t
    if "anyOf" in spec:
        types = [s.get("type") for s in spec["anyOf"] if s.get("type") and s.get("type") != "null"]
        return " | ".join(types) if types else "any"
    return "any"


def _render_tool(tool) -> list[str]:
    schema = tool.inputSchema or {}
    props = schema.get("properties") or {}
    required = set(schema.get("required") or [])
    lines = [f"### `{tool.name}`", "", (tool.description or "").strip(), ""]
    if not props:
        lines.append("_No parameters._")
        lines.append("")
        return lines
    for name, spec in props.items():
        flag = "required" if name in required else "optional"
        desc = (spec.get("description") or "").strip()
        default = spec.get("default")
        bits = [_param_type(spec), flag]
        if default not in (None, "") and name not in required:
            bits.append(f"default={default!r}")
        suffix = f" — {desc}" if desc else ""
        lines.append(f"- `{name}` ({', '.join(bits)}){suffix}")
    lines.append("")
    return lines


async def _gather() -> str:
    tools = sorted(await mcp.list_tools(), key=lambda t: t.name)
    resources = sorted(await mcp.list_resources(), key=lambda r: str(r.uri))
    templates = sorted(await mcp.list_resource_templates(), key=lambda t: t.uriTemplate)
    prompts = sorted(await mcp.list_prompts(), key=lambda p: p.name)

    out: list[str] = [
        "# mcp-apple-reminders — capability catalog",
        "",
        (
            f"Auto-generated by `scripts/gen_tools_doc.py` from the live FastMCP server. "
            f"**{len(tools)} tools**, **{len(resources)} static resources + {len(templates)} templated**, "
            f"**{len(prompts)} prompts**. Regenerate with `make gen-tools-doc`."
        ),
        "",
        "## Tools",
        "",
    ]
    for tool in tools:
        out.extend(_render_tool(tool))

    out += ["## Resources", ""]
    for r in resources:
        out.append(f"- `{r.uri}` — {(r.name or '').strip()}{(': ' + r.description.strip()) if r.description else ''}")
    out += ["", "## Resource templates", ""]
    for t in templates:
        out.append(
            f"- `{t.uriTemplate}` — {(t.name or '').strip()}"
            f"{(': ' + t.description.strip()) if t.description else ''}"
        )
    out += ["", "## Prompts", ""]
    for p in prompts:
        args = getattr(p, "arguments", None) or []
        arg_sig = ", ".join(f"{a.name}{'' if a.required else '?'}" for a in args)
        out.append(f"### `{p.name}({arg_sig})`")
        out.append("")
        if p.description:
            out.append(p.description.strip())
            out.append("")
        for a in args:
            flag = "required" if a.required else "optional"
            desc = f" — {a.description.strip()}" if a.description else ""
            out.append(f"- `{a.name}` ({flag}){desc}")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    content = asyncio.run(_gather())
    _OUT.write_text(content)
    print(f"✓ wrote {_OUT.relative_to(_OUT.parent.parent)} ({content.count(chr(10)) + 1} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
